# html lang
language: en

# main menu navigation
menu:
  Home: '/#details'
  Work: '/#recent-posts'
  Feedback: '/#feedback'
  Contact: '/#contact'

# Miscelaneous
favicon: /favicon.png

# loaded in the head
stylesheets:
- /css/style.css

# scripts - loaded before end of body
scripts:
- /scripts/navsync.min.js
- /scripts/ui-enhancements.js

# sass configuration
node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false
  
#Social Media Buttons
twitter: r_p4rk
codepen: r_p4rk
github: rp4rk

#Google Analytics ID
google: UA-66628281-1